# Generated by Django 3.0.3 on 2020-04-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadb',
            name='date',
        ),
        migrations.RemoveField(
            model_name='datadb',
            name='text',
        ),
        migrations.AddField(
            model_name='datadb',
            name='review',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='datadb',
            name='가격',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='datadb',
            name='거래방법',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='datadb',
            name='위치',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
