# Generated by Django 3.0.5 on 2020-04-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200401_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadb',
            name='가격',
        ),
        migrations.RemoveField(
            model_name='datadb',
            name='거래방법',
        ),
        migrations.RemoveField(
            model_name='datadb',
            name='위치',
        ),
        migrations.AddField(
            model_name='datadb',
            name='howtotrade',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='datadb',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='datadb',
            name='photo',
            field=models.ImageField(default='product', upload_to='product'),
        ),
        migrations.AddField(
            model_name='datadb',
            name='price',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='datadb',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
