# Generated by Django 3.0.5 on 2020-04-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200401_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadb',
            name='photo',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
    ]
