# Generated by Django 3.0.3 on 2020-03-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='createDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, choices=[('person', 'Person'), ('product', 'Product'), ('place', 'Place')], max_length=7, null=True)),
                ('Project_Name', models.CharField(max_length=50)),
                ('Saved', models.CharField(max_length=50)),
                ('Created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
