# Generated by Django 3.0.3 on 2020-03-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companydb_hi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydb',
            name='hi',
        ),
    ]
